project:
  type: website
  output-dir: docs
  resources:
    - atwood.txt

reticulate:
  python: "/Users/xinchen/miniforge3/envs/qenv/bin/python"

website:
  title: "CSc 345 Analysis of Discrete Structures"
  google-analytics: ""
  sidebar:
    style: "docked"
    background: primary
    search: true
    contents:
      - section: "Start Here"
        contents: 
        - syllabus.pdf
        - tas.qmd
        - grading.qmd
        - academic-integrity.qmd
      - section: "Programming Projects"
        contents: 
        - style.qmd
      - section: "Homeworks"
        contents: 
        - short-projects.qmd
      - section: "Topic 1: Review"
        contents:
        - grading.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    number-sections: false

editor: source

