project:
  type: website
  output-dir: docs
  resources:
    - atwood.txt

reticulate:
  python: "/Users/xinchen/miniforge3/envs/qenv/bin/python"

website:
  title: "CSc 345 Analysis of Discrete Structures"
  google-analytics: ""
  sidebar:
    style: "docked"
    background: primary
    search: true
    contents:
      - section: "Start Here"
        contents: 
        - text: "Syllabus"
          href: "syllabus.pdf"
        - academic-integrity.qmd
        - tas.qmd
      - section: "Programming Projects"
        contents: 
        - style.qmd
        - pp1.qmd
      - section: "Homeworks"
        contents: 
        - hw1.qmd
        - hw2.qmd
      - section: "Topic 1: Review"
        contents:
        - text: "Syllabus Presentation"
          href: "Syllabus Presentation.pptx"
        - text: "Topic 1 Slides"
          href: "Topic 1 Slides.pdf"
      - section: "Topic 2: Algorithm Analysis"
        contents:
        - text: "Topic 2 Slides"
          href: "Topic 2 Slides.pdf"
      - section: "Topic 3: Graphs"
        contents:
        - text: "Topic 3 Slides"
          href: "Topic 3 Slides.pdf"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    number-sections: false

editor: source

